name: GCC Build x64
description: Builds and tests the project under latest ubuntu with GCC
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  GCC-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: CMake generate build files
        run: >
          cmake 
          -S .
          -DENABLE_SANDBOX=1
          -DENABLE_TESTING=1
          -DWARNINGS_AS_ERRORS=1
          -DDEFINE_SI_CONSTANTS=1
          -DENABLE_BIG_INT_STD_INTEGRATION=1
          -DENABLE_BIG_INT_UTIL=1
          -DENABLE_BIG_INT_LITERAL=1
      - name: CMake build regular targets
        run: cmake --build . --verbose
      - name: CMake build test target
        run: cmake --build . --verbose --target ALL_TESTS
      - name: Run unit tests
        run: >
          ctest 
          -C Debug
          --output-on-failure
          --schedule-random
  # no-using-namespace-in-header-files:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: true
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: false # we don't want to check the submodules for this lint
  #     - name: Search for `using namespace`
  #       run: >
  #         test `grep -rF "using namespace" /include/*.h include/*.hpp | wc -l` 
  #         -eq 0
