name: GCC Build x64
on: [push, pull_request, workflow_dispatch]

jobs:
  GCC-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: CMake generate build files
        run: >
          cmake 
          -S .
          -DENABLE_SANDBOX=1
          -DENABLE_TESTING=1
          -DWARNINGS_AS_ERRORS=1
          -DDEFINE_SI_CONSTANTS=1
          -DENABLE_BIG_INT_STD_INTEGRATION=1
          -DENABLE_BIG_INT_UTIL=1
          -DENABLE_BIG_INT_LITERAL=1
      - name: CMake build
        run: cmake --build .  --verbose
      - name: Run unit tests
        run: >
          ctest 
          -C Debug
          --output-on-failure
          --build-target ALL_TESTS
          --schedule-random
